### PR TITLE
Recommended Index

### PR DESCRIPTION
**Pull request by raineorshine**
It is recommended that users create the following [compound index](https://www.mongodb.com/docs/manual/core/indexes/index-types/index-compound/) on their MongoDB instance to improve query performance:

```js
db['yjs-writings'].createIndex({
	version: 1,
	docName: 1,
	action: 1,
	clock: 1,
	part: 1,
});
```

From what I can tell, this one index covers all queries currently used:

- `{ version }` - Used by `getAllSVDocs`
- `{ version, docName }` - Used by `createDocumentStateVectorKey`
- `{ version, docName, action }` - Used by `getMongoUpdates`
- `{ version, docName, action, clock }` - Used by `getCurrentUpdateClock` and `storeUpdate`
- `{ version, docName, action, clock, part }` - Used by `storeUpdate`

This PR adds this recommendation to the README.

### CODE REVIEW

**Comment by MaxNoetzold** [comment]
Thank you!

 merged it because it makes sense for some use cases/users. I have some more thoughts on it and may implement them sometime:

This only works for the default configuration of the provider (collectionName: 'yjs-writings', multipleCollections: false). While it shouldn't be a problem for users who change the collectionName to also change the example code you provided, it is not really usable if multipleCollections are turned on. This should probably be built into the library as a function that either automatically creates one for each collection or that can be called by the user.

**Comment by MaxNoetzold** [comment]
Additionally MongoDB [doesnt support to change the sort order of the index](https://www.mongodb.com/docs/manual/core/indexes/index-types/index-compound/sort-order/#unsupported-queries). This, however, is needed for the function `getCurrentUpdateClock` (or `getMongoUpdates` if the opts.reverse is set to true). But I guess that this fact can be ignored since the code will keep working. It just wont use the index.

**Comment by raineorshine** [comment]
Got it, makes sense. I haven't used `multipleCollections: true` yet. I'm not sure the advantage of multiple collections as long as you have an index on `docName`.

The majority of queries will use the index, as you pointed out, but you're right, there are exceptions.

Thanks!

**Comment by MaxNoetzold** [comment]
> I'm not sure the advantage of multiple collections as long as you have an index on docName.

As I see it, it's probably irrelevant which solution you choose. 

The [MongoDB docs](https://www.mongodb.com/docs/manual/core/data-model-operations/#large-number-of-collections) state the following about multiple collections:

> Generally, having a large number of collections has no significant performance penalty and results in very good performance. Distinct collections are very important for high-throughput batch processing.

And [it says](https://www.mongodb.com/docs/manual/core/data-model-operations/#indexes) this about indexing: 

> Adding an index has some negative performance impact for write operations. For collections with high write-to-read ratio, indexes are expensive since each insert must also update any indexes.
When active, each index consumes disk space and memory. This usage can be significant and should be tracked for capacity planning, especially for concerns over working set size.

So there is an argument for `multipleCollections` if you have **a lot** of ydocs to store. But in reality, it doesn't seem to matter.

However, I should probably change that the `docName` is stored and used even if you use `multipleCollections`. Otherwise this grouping optimization has even fewer advantages.

**Comment by raineorshine** [comment]
Yeah, that’s very interesting. As a point of contrast, I had to re-write y-indexeddb for the exact opposite reason: a separate collection per doc reduced performance and caused the browser to crash after a certain number of docs. Indexes are essential to IndexedDB performance. 

I might do some performance testing of `multipleCollections` on my data set. I have hundreds of thousands of docs (it's a large graph) so these difference really add up for me.

**Comment by MaxNoetzold** [comment]
>  Indexes are essential to **Index**edDB performance.

I mean, this info is hidden in plain sight: in the name. ^^

Jokes aside, this is really interesting. I might actually get to that point as well, even though I will probably just have a few hundred docs. Which of your y-indexeddb branches would be the correct one to use for this?

> I might do some performance testing of multipleCollections on my data set.

I am very interested in your results.

I will implement the mentioned optimizations to `multipleCollections` when I have the time. Maybe they'll help you out as well

**Comment by raineorshine** [comment]
> > Indexes are essential to **Index**edDB performance.
> 
> I mean, this info is hidden in plain sight: in the name. ^^

It all makes sense!!!

> Which of your y-indexeddb branches would be the correct one to use for this?

It's on [y-indexeddb-multiplex](https://github.com/raineorshine/y-indexeddb/blob/y-indexeddb-multiplex/src/y-indexeddb.js)

> I am very interested in your results.
> 
> I will implement the mentioned optimizations to `multipleCollections` when I have the time. Maybe they'll help you out as well

Thanks!

I have a memory leak in my application to focus on now, but if I end up doing some more performance optimization and testing out `multipleCollections` I'll let you know.

**Pull request merged**
