### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by raineorshine**
This PR adds types for better autocomplete and use in Typescript projects.

It uses the same setup as y-leveldb.

### CODE REVIEW

**Comment by MaxNoetzold** [comment]
This looks really cool, thank you. I'll merge it next week

**Comment by raineorshine** [comment]
Sure!

Note that I had to make some of the deconstructed opts arguments required because I was getting type errors. Strange, since y-leveldb compiles fine with optional deconstructed args. I tried a couple different versions of typescript but it still errored, so it must be something else.

**Comment by MaxNoetzold** [comment]
> Note that I had to make some of the deconstructed opts arguments required because I was getting type errors. Strange, since y-leveldb compiles fine with optional deconstructed args.

In y-leveldb, he is using optional destructured arguments in a slightly different way. Instead of `readAsCursor(query, { limit, reverse } = {})`, he wrote `readAsCursor(query, { limit = 0, reverse = false } = {})`. As soon as I make this change, it works with your TypeScript configuration. I will incorporate this change into your code tomorrow and then merge it.

**Comment by MaxNoetzold** [comment]
I wasnt able to push to your repo so I instead created a new branch and a new [PR](https://github.com/MaxNoetzold/y-mongodb-provider/pull/3). I dont have a lot of experiences with open source contribution :D

**Comment by raineorshine** [comment]
No worries!

For future reference: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by MaxNoetzold** [comment]
> For future reference: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

Thank you, but I think the following was the problem, wasnt it?
> Only the user who created the pull request can give you permission to push commits to the user-owned fork.

**Comment by raineorshine** [comment]
~That option is selected by default, so it would have been set automatically when I created the PR.~ Yup, the option was off for some reason :).

**Pull request closed without merging**
